"""
Notes from Paul,
    #try reducing step size 
    #try calculating the largest eigenvalue rather than all of them
    #https://iterativesolvers.julialinearalgebra.org/stable/eigenproblems/power_method/
    julia -t 8
"""

#!/usr/bin/env julia
# Boundary scan over canonical model files generated by new_code/generate_bank.jl.
# Example:
#   julia --startup-file=no new_code/boundary_scan.jl 1_bank_50_models_n_2-7_100_dirs_b_dirichlet
#   julia --startup-file=no new_code/boundary_scan.jl 1_bank_50_models_n_2-7_100_dirs_b_dirichlet --model-file model_n_3_seed_40000002_n_dirs_100.json
# All scan settings are in pipeline_config.jl.

using LinearAlgebra
using JSON3
using HomotopyContinuation

include(joinpath(@__DIR__, "pipeline_config.jl"))
include(joinpath(@__DIR__, "model_store_utils.jl"))
include(joinpath(@__DIR__, "utils", "json_utils.jl"))
include(joinpath(@__DIR__, "utils", "hc_param_utils.jl"))
include(joinpath(@__DIR__, "utils", "glvhoi_utils.jl"))

# Raise a usage error with the supported CLI arguments and chunk-mode options.
function usage_error()
    msg = """
    Usage:
      julia --startup-file=no new_code/boundary_scan.jl <run_dir> [--model-file FILE]
                              [--dir-chunk-start INT --dir-chunk-end INT]

    Required:
      <run_dir>               Folder inside new_code/model_runs/

    Options:
      --model-file FILE       Scan only one model JSON file from the run folder
      --dir-chunk-start INT   0-based inclusive start direction index (chunk mode)
      --dir-chunk-end   INT   0-based inclusive end direction index (chunk mode)

    Both --dir-chunk-start and --dir-chunk-end must be provided together to activate
    chunk mode. In chunk mode results are written to a separate file:
      <model_stem>_chunk_<START>_<END>.json

    All scan settings (alpha_grid, max_pert, preboundary_frac, etc.) are in pipeline_config.jl.
    """
    error(msg)
end

# Parse CLI arguments into run, model-selection, and optional chunk-scan settings.
function parse_args(args::Vector{String})
    isempty(args) && usage_error()

    run_dir         = ""
    model_file      = nothing
    dir_chunk_start = nothing
    dir_chunk_end   = nothing

    i = 1
    while i <= length(args)
        arg = args[i]
        if arg == "--model-file" && i < length(args)
            model_file = args[i + 1]
            i += 2
        elseif arg == "--dir-chunk-start" && i < length(args)
            dir_chunk_start = parse(Int, args[i + 1])
            i += 2
        elseif arg == "--dir-chunk-end" && i < length(args)
            dir_chunk_end = parse(Int, args[i + 1])
            i += 2
        elseif startswith(arg, "--")
            error("Unknown flag: $arg. Configure scan settings in pipeline_config.jl.")
        elseif run_dir == ""
            run_dir = arg
            i += 1
        else
            error("Unexpected argument: $arg")
        end
    end

    run_dir == "" && usage_error()

    # Validate chunk args: both or neither
    if isnothing(dir_chunk_start) != isnothing(dir_chunk_end)
        error("--dir-chunk-start and --dir-chunk-end must be provided together.")
    end
    if !isnothing(dir_chunk_start) && dir_chunk_start > dir_chunk_end
        error("--dir-chunk-start ($dir_chunk_start) must be <= --dir-chunk-end ($dir_chunk_end).")
    end

    return (run_dir=run_dir, model_file=model_file,
            dir_chunk_start=dir_chunk_start, dir_chunk_end=dir_chunk_end)
end

# --------------------------- boundary tracking (HC) ----------------------------

mutable struct ScanWorkspace{TTracker,TCompiled}
    tracker::TTracker
    compiled_system::TCompiled
    p_start::Vector{Float64}
    p_target::Vector{Float64}
    p_eval::Vector{Float64}
    f_eval::Vector{Float64}
    jac_f::Matrix{Float64}
    jac_comm::Matrix{Float64}
    x_eval::Vector{Float64}
end

# Build reusable HC buffers and tracker state for repeated scans of one system.
function ScanWorkspace(syst::System, n_params::Int)
    p_start  = zeros(Float64, n_params)
    p_target = zeros(Float64, n_params)
    p_eval   = zeros(Float64, n_params)
    H = ParameterHomotopy(syst, p_start, p_target)
    tracker = Tracker(H; options=TrackerOptions(max_steps=MAX_STEPS_PT))
    compiled_system = CompiledSystem(syst)
    n_state = length(syst.variables)
    f_eval   = Vector{Float64}(undef, n_state)
    jac_f    = Matrix{Float64}(undef, n_state, n_state)
    jac_comm = Matrix{Float64}(undef, n_state, n_state)
    x_eval   = Vector{Float64}(undef, n_state)
    return ScanWorkspace(tracker, compiled_system,
                         p_start, p_target, p_eval,
                         f_eval, jac_f, jac_comm, x_eval)
end

# Reset the start and target parameter vectors before scanning a new direction.
@inline function reset_ray_parameters!(ws::ScanWorkspace)
    fill!(ws.p_start,  0.0)
    fill!(ws.p_target, 0.0)
    return ws
end

# Fill the workspace target parameter vector with the perturbation ray endpoint.
@inline function set_ray_target!(ws::ScanWorkspace,
                                 u::AbstractVector{<:Real},
                                 max_pert_mag::Real)
    @inbounds for i in eachindex(u)
        ws.p_target[i] = max_pert_mag * u[i]
    end
    return ws.p_target
end

# Reinitialize the HC tracker for a new start state and parameter segment.
function reset_tracker!(ws::ScanWorkspace,
                        x_start::AbstractVector,
                        p_start::AbstractVector{<:Real},
                        p_target::AbstractVector{<:Real};
                        max_step_ratio::Float64=0.3)
    par_dist = parameter_distance(p_start, p_target)
    start_parameters!(ws.tracker, p_start)
    target_parameters!(ws.tracker, p_target)
    init!(ws.tracker, x_start, 1.0, 0.0; max_initial_step_size=par_dist * max_step_ratio)
    return par_dist
end

# Evaluate the dominant community-matrix eigenvalue for the current equilibrium.
function lambda_max_equilibrium_hc!(ws::ScanWorkspace,
                                    x::AbstractVector{<:Real},
                                    p::AbstractVector{<:Real})
    evaluate_and_jacobian!(ws.f_eval, ws.jac_f, ws.compiled_system, x, p)
    mul!(ws.jac_comm, Diagonal(x), ws.jac_f)
    e = eigvals!(ws.jac_comm)
    return maximum(real, e)
end

include(joinpath(@__DIR__, "utils", "boundary_event_utils.jl"))

# Track one equilibrium all the way to a target parameter vector.
function track_to_params!(ws::ScanWorkspace,
                          x_start::AbstractVector,
                          p_start::AbstractVector{<:Real},
                          p_target::AbstractVector{<:Real};
                          max_step_ratio::Float64=0.3)
    reset_tracker!(ws, x_start, p_start, p_target; max_step_ratio=max_step_ratio)

    while is_tracking(ws.tracker.state.code)
        HomotopyContinuation.step!(ws.tracker)
    end

    @inbounds @simd for i in eachindex(ws.x_eval, ws.tracker.state.x)
        ws.x_eval[i] = real(ws.tracker.state.x[i])
    end
    return (x=copy(ws.x_eval), status=ws.tracker.state.code)
end

# Recover the equilibrium slightly before the detected boundary point.
function preboundary_equilibrium(ws::ScanWorkspace,
                                 x0::AbstractVector,
                                 p_start::AbstractVector{<:Real},
                                 Δrcrit::AbstractVector{<:Real},
                                 frac::Real)
    p_minus = ws.p_eval
    @inbounds for i in eachindex(Δrcrit)
        p_minus[i] = frac * Δrcrit[i]
    end
    if parameter_distance(p_minus, p_start) == 0.0
        return collect(Float64.(x0))
    end
    res = track_to_params!(ws, x0, p_start, p_minus)
    return res.x
end

# Scan one perturbation direction with HC and package the boundary summary.
function scan_ray(ws::ScanWorkspace,
                  x0::AbstractVector{<:Real},
                  r0::AbstractVector{<:Real},
                  u::AbstractVector{<:Real};
                  max_pert_mag::Real,
                  preboundary_frac::Real=SCAN_PREBOUNDARY_FRAC)
    n = length(x0)
    @assert length(u) == n
    @assert abs(norm(u) - 1) < 1e-8
    @assert length(ws.p_start) == n

    reset_ray_parameters!(ws)
    set_ray_target!(ws, u, max_pert_mag)

    event, t_end, x_crit = find_event(ws.p_start, ws.p_target,
                                       collect(Float64.(x0)), ws, ZERO_ABUNDANCE;
                                       check_stability=SCAN_CHECK_STABILITY,
                                       λ_tol=SCAN_LAMBDA_TOL)
    t_real  = real(t_end)
    drcrit  = (1 - t_real) .* ws.p_target
    rcrit   = collect(r0 .+ drcrit)
    delta_c = norm(drcrit)
    x_pre   = preboundary_equilibrium(ws, x0, ws.p_start, drcrit, preboundary_frac)

    return (flag=event,
            status=:step_refined,
            drcrit=drcrit,
            rcrit=rcrit,
            delta_c=delta_c,
            x_preboundary=collect(x_pre),
            x_crit=x_crit,
            p_crit=drcrit)
end

# Analytically scan one direction for the alpha=0 linear fallback system.
function scan_ray_linear_alpha0(A::AbstractMatrix{<:Real},
                                A_fac,
                                x_base::AbstractVector{<:Real},
                                r0::AbstractVector{<:Real},
                                u::AbstractVector{<:Real};
                                max_pert_mag::Real,
                                preboundary_frac::Real=SCAN_PREBOUNDARY_FRAC,
                                λ_tol::Float64=SCAN_LAMBDA_TOL,
                                unstable_scan_steps::Int=SCAN_UNSTABLE_STEPS)
    n = length(r0)
    @assert size(A, 1) == n && size(A, 2) == n
    @assert length(x_base) == n
    @assert length(u) == n
    @assert abs(norm(u) - 1) < 1e-8

    dx = -(A_fac \ u)
    x_tmp = Vector{Float64}(undef, n)
    jac_tmp = Matrix{Float64}(undef, n, n)

    # Update the temporary equilibrium state at displacement s along the ray.
    function fill_x!(s::Float64)
        @inbounds @simd for i in 1:n
            x_tmp[i] = x_base[i] + s * dx[i]
        end
        return x_tmp
    end

    # Return the minimum abundance at displacement s.
    function min_x_at(s::Float64)
        fill_x!(s)
        return minimum(x_tmp)
    end

    # Return the dominant community-matrix eigenvalue at displacement s.
    function lambda_at(s::Float64)
        fill_x!(s)
        @inbounds for i in 1:n
            xi = x_tmp[i]
            for j in 1:n
                jac_tmp[i, j] = xi * A[i, j]
            end
        end
        return maximum(real, eigvals(jac_tmp))
    end

    # Shrink an event bracket until it reaches the configured parameter tolerance.
    function bisection_interval(is_event, s_lo::Float64, s_hi::Float64)
        depth = 0
        lo = s_lo
        hi = s_hi
        while depth < MAX_ITERS && (hi - lo) > PARAM_TOL
            mid = 0.5 * (lo + hi)
            if is_event(mid)
                hi = mid
            else
                lo = mid
            end
            depth += 1
        end
        return lo, hi, depth
    end

    # Earliest negative equilibrium crossing.
    s_neg = Inf
    if minimum(x_base) <= ZERO_ABUNDANCE
        s_neg = 0.0
    else
        @inbounds for i in 1:n
            di = dx[i]
            if di < 0.0
                si = (ZERO_ABUNDANCE - x_base[i]) / di
                if 0.0 <= si < s_neg
                    s_neg = si
                end
            end
        end
    end
    if !isfinite(s_neg) || s_neg > max_pert_mag
        s_neg = Inf
    end

    s_neg_lo = 0.0
    s_neg_hi = s_neg
    depth_neg = 0
    if isfinite(s_neg) && s_neg > 0.0
        s_neg_lo, s_neg_hi, depth_neg = bisection_interval(s -> min_x_at(s) <= ZERO_ABUNDANCE, 0.0, s_neg)
    end

    # Earliest instability crossing while still before negativity.
    s_unstable = Inf
    s_unstable_lo = 0.0
    s_unstable_hi = Inf
    depth_unstable = 0
    λ0 = SCAN_CHECK_STABILITY ? lambda_at(0.0) : Inf
    if SCAN_CHECK_STABILITY && λ0 <= λ_tol
        s_limit = min(max_pert_mag, isfinite(s_neg) ? s_neg : max_pert_mag)
        if s_limit > 0.0 && lambda_at(s_limit) > λ_tol
            bracket_found = false
            lo = 0.0
            hi = s_limit
            λ_prev = λ0
            s_prev = 0.0
            for k in 1:unstable_scan_steps
                s_k = s_limit * (k / unstable_scan_steps)
                λ_k = lambda_at(s_k)
                if λ_prev <= λ_tol && λ_k > λ_tol
                    lo = s_prev
                    hi = s_k
                    bracket_found = true
                    break
                end
                s_prev = s_k
                λ_prev = λ_k
            end
            if !bracket_found
                lo = 0.0
                hi = s_limit
            end
            s_unstable_lo, s_unstable_hi, depth_unstable =
                bisection_interval(s -> lambda_at(s) > λ_tol, lo, hi)
            s_unstable = s_unstable_hi
        end
    end

    flag::Symbol = :success
    status::Symbol = :success
    depth = 0
    s_pos = max_pert_mag
    s_crit = max_pert_mag

    if isfinite(s_neg) && (!isfinite(s_unstable) || s_neg <= s_unstable)
        flag = :negative
        status = :linear_analytic
        depth = depth_neg
        s_pos = s_neg_lo
        s_crit = s_neg_hi
    elseif isfinite(s_unstable)
        flag = :unstable
        status = :linear_analytic
        depth = depth_unstable
        s_pos = s_unstable_lo
        s_crit = s_unstable_hi
    end

    dr_pos = s_pos .* u
    dr_crit = s_crit .* u
    rcrit = collect(r0 .+ dr_crit)

    x_pre = if s_crit == 0.0
        collect(x_base)
    else
        fill_x!(preboundary_frac * s_crit)
        collect(x_tmp)
    end
    fill_x!(s_crit)
    x_crit = collect(x_tmp)

    p_pos = collect(dr_pos)
    p_crit = collect(dr_crit)

    return (flag=flag,
            status=status,
            depth=depth,
            drcrit=collect(dr_crit),
            rcrit=rcrit,
            delta_c=norm(dr_crit),
            x_preboundary=x_pre,
            p_pos=p_pos,
            p_crit=p_crit,
            x_crit=x_crit)
end

# ------------------------------ model scan ------------------------------

# Scan every requested direction for one model across the configured alpha grid.
function scan_model(model::Dict{String,Any}; dir_range::Union{Nothing,Tuple{Int,Int}}=nothing)
    ctx = build_hc_system(model)
    n, n_dirs = ctx.n, ctx.n_dirs
    alpha_results = Vector{Any}()

    for (a_idx, alpha) in enumerate(ctx.alpha_grid)
        ws = ctx.make_workspace(alpha)
        r0_val = ctx.baseline_r isa Function ? ctx.baseline_r(alpha) : ctx.baseline_r

        ray_indices = isnothing(dir_range) ? (1:n_dirs) : (dir_range[1]+1 : dir_range[2]+1)
        dir_results = Vector{Any}(undef, length(ray_indices))

        for (local_idx, ray_id) in enumerate(ray_indices)
            u_raw = @view ctx.U[:, ray_id]
            nrm = norm(u_raw)
            nrm > 0 || error("Direction ray_id=$ray_id has zero norm.")
            u = collect(u_raw ./ nrm)

            res = if ws === nothing
                lf = ctx.linear_fallback
                scan_ray_linear_alpha0(lf.A, lf.A_fac, lf.x_base_linear,
                                       r0_val, u; max_pert_mag=SCAN_MAX_PERT)
            else
                x0_val = ctx.x0 isa Function ? ctx.x0(alpha) : ctx.x0
                scan_ray(ws, x0_val, r0_val, u; max_pert_mag=SCAN_MAX_PERT)
            end

            row = Dict{String,Any}(
                "ray_id" => ray_id, "flag" => String(res.flag),
                "status" => string(res.status), "drcrit" => res.drcrit,
                "rcrit" => res.rcrit, "delta_c" => Float64(res.delta_c),
                "x_preboundary" => res.x_preboundary, "x_boundary" => res.x_crit,
            )
            dir_results[local_idx] = row
        end

        push!(alpha_results, Dict(
            "alpha_idx" => a_idx, "alpha" => alpha, "directions" => dir_results,
        ))
    end

    scanned_start = isnothing(dir_range) ? 1      : dir_range[1] + 1
    scanned_end   = isnothing(dir_range) ? n_dirs : dir_range[2] + 1

    output = Dict{String,Any}()
    for (k, v) in model; output[k] = v; end
    scan_cfg = Dict{String,Any}(
        "alpha_grid" => ctx.alpha_grid, "max_pert" => SCAN_MAX_PERT,
        "preboundary_fraction" => SCAN_PREBOUNDARY_FRAC,
        "max_bisection_iters" => MAX_ITERS, "x_tol" => ZERO_ABUNDANCE,
        "param_tol" => PARAM_TOL,
        "scanned_dir_start" => scanned_start, "scanned_dir_end" => scanned_end,
    )
    if !isnothing(dir_range)
        scan_cfg["dir_start"] = dir_range[1]
        scan_cfg["dir_end"]   = dir_range[2]
    end
    output["scan_config"] = scan_cfg
    output["scan_results"] = alpha_results
    haskey(output, "post_dynamics_results") && delete!(output, "post_dynamics_results")
    haskey(output, "backtrack_results")     && delete!(output, "backtrack_results")
    return output
end

# ------------------------------ main ------------------------------

# Load requested models, run the boundary scan, and write the resulting JSON payloads.
function main()
    opts = parse_args(ARGS)
    run_root = canonical_models_root(@__DIR__, opts.run_dir)
    isdir(run_root) || error("Run directory not found: $run_root")
    model_paths = resolve_model_paths(run_root, opts.model_file)

    dir_chunk_start = opts.dir_chunk_start
    dir_chunk_end   = opts.dir_chunk_end
    chunk_mode      = !isnothing(dir_chunk_start)

    println("Boundary scan")
    println("  run: $run_root")
    println("  models: $(length(model_paths))")
    println("  alpha_grid: $SCAN_ALPHA_GRID (gibbs models use alpha_eff from JSON)")
    println("  max_pert: $SCAN_MAX_PERT")
    println("  preboundary_fraction: $SCAN_PREBOUNDARY_FRAC")
    if chunk_mode
        println("  chunk mode: directions $(dir_chunk_start)-$(dir_chunk_end) (0-based)")
        println("  output: separate chunk files")
    else
        println("  output: canonical model files in-place")
    end

    n_models = length(model_paths)
    for (idx, model_path) in enumerate(model_paths)
        model_name = basename(model_path)
        println("[$idx/$n_models] scanning $model_name")

        model = to_dict(JSON3.read(read(model_path, String)))

        # Validate chunk bounds against this model's n_dirs
        dir_range = nothing
        if chunk_mode
            n_dirs_model = Int(model["n_dirs"])
            if dir_chunk_start < 0 || dir_chunk_end >= n_dirs_model
                @warn "Chunk [$dir_chunk_start, $dir_chunk_end] out of range for $model_name (n_dirs=$n_dirs_model). Skipping."
                continue
            end
            dir_range = (dir_chunk_start, dir_chunk_end)
        end

        payload = scan_model(model; dir_range=dir_range)

        if chunk_mode
            payload["chunk_info"] = Dict("dir_start" => dir_chunk_start, "dir_end" => dir_chunk_end)
            stem = splitext(basename(model_path))[1]
            chunk_filename = "$(stem)_chunk_$(dir_chunk_start)_$(dir_chunk_end).json"
            out_path = joinpath(dirname(model_path), chunk_filename)
        else
            out_path = model_path
        end

        safe_write_json(out_path, payload)
        println("      wrote $(basename(out_path))")
    end

    println("Done.")
end

if abspath(PROGRAM_FILE) == @__FILE__
    main()
end
