#!/usr/bin/env python3
"""
n2_feasibility_domains.py — reproduce the n=2 feasibility-domain row figure
using data generated by generate_n2_boundary_data.jl.

Usage:
    python n2_feasibility_domains.py [boundary_data_dir] [output.pdf]

Defaults:
    boundary_data_dir = boundary_data/
    output            = pdffiles/main/alphas_deltar_row_py.pdf
"""
import os
import sys
import json
import subprocess
import tempfile
import shutil

import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.colors import TwoSlopeNorm
from matplotlib.patches import FancyArrowPatch
import matplotlib.gridspec as gridspec

# ═══════════════════════════ typography (match hysteresis_two_routes.py) ════

plt.rcParams.update({
    "font.family":      "serif",
    "mathtext.fontset": "cm",
    "font.size":        9,
    "axes.labelsize":   10,
    "axes.titlesize":   10,
    "axes.linewidth":   0.7,
    "xtick.direction":  "in",
    "ytick.direction":  "in",
    "xtick.major.size": 3.5,
    "ytick.major.size": 3.5,
    "legend.frameon":   False,
    "legend.fontsize":  9.75,
})

# ═══════════════════════════ configuration ═══════════════════════════════════

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_DATA_DIR = os.path.join(SCRIPT_DIR, "boundary_data")
DEFAULT_OUTFILE = os.path.join(os.path.dirname(SCRIPT_DIR), "pdffiles", "main", "alphas_deltar_row_py.pdf")

# Colors (matching CairoMakie original)
BG_COLOR = "#F6F2E8"
CX_COLOR = "#a200ff"  # purple for fold/unstable boundary
NEG_COLOR = "black"

# Font sizes — relative to rcParams base (9pt), +40%
TICK_FS = 11.2
AXLAB_FS = 14
PANELTAG_FS = 16.8
LEG_FS = 12.6
CBTICK_FS = 11.2
CBLABEL_FS = 14

# Line widths
NEG_LW = 1.5
CX_LW = 1.8
SEG_LW = 1.0

# Marker sizes (for ax.plot, diameter in points)
HIT_MS = 4.5
CROSS_MS = 7
SHARED_MS = 5

# Faint rays on panel a (must match n_perts in generate_n2_boundary_data.jl)
N_RAYS = 64
FAINT_RAY_COLOR = "#8a8a8a"
FAINT_RAY_LW = 0.45
FAINT_RAY_ALPHA = 0.55

# ═══════════════════════════ data loading ════════════════════════════════════

def load_data(data_dir):
    """Load all boundary data from directory."""
    with open(os.path.join(data_dir, "metadata.json")) as f:
        meta = json.load(f)

    xs = np.load(os.path.join(data_dir, "xs.npy"))
    ys = np.load(os.path.join(data_dir, "ys.npy"))

    ncols = len(meta["panels"])
    panels = []
    for j in range(ncols):
        pdir = os.path.join(data_dir, f"panel_{j}")
        p = {
            "Zneg": np.load(os.path.join(pdir, "Zneg.npy")),
            "Zcx":  np.load(os.path.join(pdir, "Zcx.npy")),
            "H":    np.load(os.path.join(pdir, "H.npy")),
            "hxs":  np.load(os.path.join(pdir, "hxs.npy")),
            "hys":  np.load(os.path.join(pdir, "hys.npy")),
        }
        p.update(meta["panels"][j])
        panels.append(p)

    return meta, xs, ys, panels


def ray_thetas():
    return np.linspace(0.0, 2.0 * np.pi, N_RAYS, endpoint=False)


def theta_from_plot_point(x_plot, y_plot):
    """Recover scan-θ from a plot-coordinate point (plot x=Δr2=sinθ, y=Δr1=cosθ)."""
    return np.arctan2(x_plot, y_plot) % (2.0 * np.pi)


def ray_index_from_point(x_plot, y_plot):
    if x_plot is None or y_plot is None:
        return None
    if not (np.isfinite(x_plot) and np.isfinite(y_plot)):
        return None
    if np.hypot(x_plot, y_plot) < 1e-12:
        return None
    theta = theta_from_plot_point(x_plot, y_plot)
    return int(round(theta * N_RAYS / (2.0 * np.pi))) % N_RAYS


def clip_to_box(ux, uy, half_x, half_y):
    """Scale (ux,uy) so it lands on the rectangle ±half_x × ±half_y."""
    if abs(ux) < 1e-12 and abs(uy) < 1e-12:
        return 0.0, 0.0
    tx = half_x / abs(ux) if abs(ux) > 1e-12 else np.inf
    ty = half_y / abs(uy) if abs(uy) > 1e-12 else np.inf
    t = min(tx, ty)
    return t * ux, t * uy


def rays_for_panel(panel, half_x, half_y):
    """For each of the N_RAYS directions, return endpoint in plot coords.

    If a numerical hit exists, the ray ends there; otherwise it extends to
    the plot-edge rectangle ±half_x × ±half_y.
    """
    hits = {}
    for hx, hy in zip(panel["neg_x"], panel["neg_y"]):
        k = ray_index_from_point(hx, hy)
        if k is not None:
            hits[k] = (hx, hy)
    for hx, hy in zip(panel["cx_x"], panel["cx_y"]):
        k = ray_index_from_point(hx, hy)
        if k is not None:
            hits[k] = (hx, hy)

    endpoints = []
    for k, theta in enumerate(ray_thetas()):
        if k in hits:
            endpoints.append(hits[k])
        else:
            ux = np.sin(theta)
            uy = np.cos(theta)
            endpoints.append(clip_to_box(ux, uy, half_x, half_y))
    return endpoints


def integer_tick_values(lo, hi, n=5):
    """Choose up to n integer tick values spanning [lo, hi]."""
    ilo = int(np.ceil(lo))
    ihi = int(np.floor(hi))
    ints = list(range(ilo, ihi + 1))
    if len(ints) <= n:
        return ints
    idx = np.round(np.linspace(0, len(ints) - 1, n)).astype(int)
    return [ints[i] for i in idx]


# ═══════════════════════════ figure construction ════════════════════════════

def make_figure(meta, xs, ys, panels, outfile):
    ncols = len(panels)
    dr1_range = meta["dr1_range"]
    dr2_range = meta["dr2_range"]
    global_min, global_max = meta["clims"]

    xticks = integer_tick_values(dr1_range[0], dr1_range[1], 5)
    yticks = integer_tick_values(dr2_range[0], dr2_range[1], 5)
    mid_panel = (ncols - 1) // 2  # 0-indexed middle panel

    # ── colormap: RdBu centered at zero ──────────────────────────────────────
    cmap = plt.get_cmap("RdBu")
    if global_min < 0 < global_max:
        norm = TwoSlopeNorm(vmin=global_min, vcenter=0, vmax=global_max)
    elif global_max <= 0:
        norm = mpl.colors.Normalize(vmin=global_min, vmax=global_max)
        cmap = plt.get_cmap("Reds_r")
    else:
        norm = mpl.colors.Normalize(vmin=global_min, vmax=global_max)
        cmap = plt.get_cmap("Blues")

    # Set NaN to transparent via a masked colormap
    cmap = cmap.copy()
    cmap.set_bad(alpha=0)

    # ── figure layout ────────────────────────────────────────────────────────
    panel_in = 2.4   # each panel width in inches
    cb_in = 0.10     # colorbar width
    cb_gap = 0.08    # gap between last panel and colorbar
    gap_in = 0.06    # gap between panels
    # Margins for y-label (left) and x-label (bottom)
    margin_l = 0.52  # left margin for y-axis label + ticks
    margin_b = 0.48  # bottom margin for x-axis label + ticks
    margin_t = 0.30  # top margin for panel tags + colorbar title
    margin_r = 0.40  # right margin for colorbar tick labels

    fig_w = margin_l + ncols * panel_in + (ncols - 1) * gap_in + cb_gap + cb_in + margin_r
    fig_h = margin_b + panel_in + margin_t

    fig = plt.figure(figsize=(fig_w, fig_h))

    # Compute subplot positions as fractions of figure
    left = margin_l / fig_w
    bottom = margin_b / fig_h
    panel_w_frac = panel_in / fig_w
    panel_h_frac = panel_in / fig_h
    gap_frac = gap_in / fig_w
    cb_gap_frac = cb_gap / fig_w
    cb_w_frac = cb_in / fig_w

    axes = []
    hm_mappable = None

    for j in range(ncols):
        ax_left = left + j * (panel_w_frac + gap_frac)
        ax = fig.add_axes([ax_left, bottom, panel_w_frac, panel_h_frac])
        ax.set_facecolor(BG_COLOR)
        ax.set_aspect("equal")

        p = panels[j]

        hxs, hys = p["hxs"], p["hys"]
        # Transpose: Makie interprets Z[i,j] as (x[i],y[j]) for square matrices,
        # matplotlib uses Z[i,j] as (x[j],y[i]).  Transposing aligns conventions.
        H = np.ma.masked_invalid(p["H"].T)

        # ── heatmap ──────────────────────────────────────────────────────────
        hm = ax.pcolormesh(hxs, hys, H, cmap=cmap, norm=norm,
                           shading="auto", rasterized=True)
        if j == ncols - 1:
            hm_mappable = hm

        # ── contour: J1 = 0 (gradual / negative boundary) ───────────────────
        ax.contour(xs, ys, p["Zneg"].T, levels=[0.0],
                   colors=NEG_COLOR, linewidths=NEG_LW)

        # ── contour: J2 = 0 (abrupt / fold-unstable boundary) ───────────────
        ax.contour(xs, ys, p["Zcx"].T, levels=[0.0],
                   colors=CX_COLOR, linewidths=CX_LW)

        # ── faint 64-direction rays (panel a only) ───────────────────────────
        if j == 0:
            half_x = 0.5 * (dr1_range[1] - dr1_range[0])
            half_y = 0.5 * (dr2_range[1] - dr2_range[0])
            shared_idx = ray_index_from_point(p["shared_x_end"],
                                              p["shared_y_end"])
            endpoints = rays_for_panel(p, half_x, half_y)
            for k, (ex, ey) in enumerate(endpoints):
                if shared_idx is not None and k == shared_idx:
                    continue
                ax.plot([0, ex], [0, ey],
                        color=FAINT_RAY_COLOR, linewidth=FAINT_RAY_LW,
                        alpha=FAINT_RAY_ALPHA, zorder=3,
                        solid_capstyle="butt")

        # ── scatter: negative boundary hits ──────────────────────────────────
        neg_x, neg_y = np.array(p["neg_x"]), np.array(p["neg_y"])
        if len(neg_x) > 0:
            ax.plot(neg_x, neg_y, "o",
                    color=NEG_COLOR, markersize=HIT_MS,
                    markeredgecolor="gray", markeredgewidth=0.5,
                    zorder=5)

        # ── scatter: fold/unstable boundary hits ─────────────────────────────
        cx_x, cx_y = np.array(p["cx_x"]), np.array(p["cx_y"])
        if len(cx_x) > 0:
            ax.plot(cx_x, cx_y, "o",
                    color=CX_COLOR, markersize=HIT_MS,
                    markeredgecolor="black", markeredgewidth=0.5,
                    zorder=5)

        # ── cross at origin ──────────────────────────────────────────────────
        ax.plot(0, 0, "+", color="black", markersize=CROSS_MS,
                markeredgewidth=1.0, zorder=6)

        # ── shared perturbation ray ──────────────────────────────────────────
        x_end = p["shared_x_end"]
        y_end = p["shared_y_end"]
        sh_flag = p["shared_flag"]
        if x_end is not None and y_end is not None and sh_flag != "none":
            is_cx = sh_flag in ("fold", "unstable")
            seg_color = CX_COLOR if is_cx else NEG_COLOR
            edge_c = "black" if is_cx else "gray"

            # Clip ray endpoint to plot box so line/arrow stay visible.
            half_x_sh = 0.5 * (dr1_range[1] - dr1_range[0])
            half_y_sh = 0.5 * (dr2_range[1] - dr2_range[0])
            inside = (abs(x_end) <= half_x_sh + 1e-9 and
                      abs(y_end) <= half_y_sh + 1e-9)
            if inside:
                xd, yd = x_end, y_end
            else:
                xd, yd = clip_to_box(x_end, y_end, half_x_sh, half_y_sh)

            # Endpoint scatter only when the actual event lies inside the plot.
            if inside:
                ax.plot(x_end, y_end, "o",
                        color=seg_color, markersize=SHARED_MS,
                        markeredgecolor=edge_c, markeredgewidth=0.8,
                        zorder=7)

            # Line: solid (no arrowhead) in panel a; dashed with arrow elsewhere
            if j == 0:
                ax.plot([0, xd], [0, yd],
                        color=seg_color, linewidth=SEG_LW,
                        linestyle="-", zorder=4)
            else:
                ax.plot([0, xd], [0, yd],
                        color=seg_color, linewidth=SEG_LW,
                        linestyle=(0, (3, 1.5)), zorder=4)

                frac = 0.08
                ax.annotate("",
                            xy=(xd, yd),
                            xytext=(xd * (1 - frac), yd * (1 - frac)),
                            arrowprops=dict(arrowstyle="-|>",
                                            color=seg_color,
                                            lw=1.0,
                                            mutation_scale=10),
                            zorder=8)

            # Label on first panel — no subscript k
            if j == 0:
                dx = dr1_range[1] - dr1_range[0]
                dy = dr2_range[1] - dr2_range[0]
                x_off = -0.12 * dx
                y_off = 0.08 * dy
                ax.text(0.5 * xd + x_off, 0.5 * yd + y_off,
                        r"$\delta_c \, \mathbf{u}$",
                        ha="center", va="center",
                        fontsize=LEG_FS * 1.15, color="black",
                        zorder=9)

        # ── panel tag (top-LEFT, outside the plot) ───────────────────────
        tag = chr(ord("a") + j)
        ax.text(-0.02, 1.02, tag, transform=ax.transAxes,
                ha="left", va="bottom", fontsize=PANELTAG_FS,
                fontweight="bold",
                zorder=10)

        # ── region labels ────────────────────────────────────────────────────
        if j == 0:
            ax.text(0.04, 0.79, "Feasible", transform=ax.transAxes,
                    ha="left", va="top", fontsize=LEG_FS, color="black")
            ax.text(0.04, 0.15, "Unfeasible", transform=ax.transAxes,
                    ha="left", va="bottom", fontsize=LEG_FS, color="black")
        if j == 2:
            ax.text(0.04, 0.15, "Complex", transform=ax.transAxes,
                    ha="left", va="bottom", fontsize=LEG_FS, color="black")

        # ── legend on panel D (j == ncols - 2) ──────────────────────────────
        if j == ncols - 2:
            from matplotlib.lines import Line2D
            handles = [
                Line2D([], [], color=CX_COLOR, linewidth=CX_LW, label="Abrupt"),
                Line2D([], [], color=NEG_COLOR, linewidth=NEG_LW, label="Gradual"),
            ]
            leg = ax.legend(handles=handles, loc="lower left",
                            fontsize=LEG_FS, frameon=False,
                            borderpad=0.4, handlelength=1.5)

        # ── axis formatting ──────────────────────────────────────────────────
        x0, x1 = hxs[0], hxs[-1]
        y0, y1 = hys[0], hys[-1]
        padx = 0.005 * (x1 - x0)
        pady = 0.005 * (y1 - y0)
        ax.set_xlim(x0 - padx, x1 + padx)
        ax.set_ylim(y0 - pady, y1 + pady)

        ax.set_xticks(xticks)
        ax.set_yticks(yticks)

        # Only middle panel gets x-tick labels; only first panel gets y-tick labels
        if j == mid_panel:
            ax.set_xlabel(
                r"Perturbation $\delta u_1$",
                fontsize=AXLAB_FS)
            ax.tick_params(axis="x", labelsize=TICK_FS)
        else:
            ax.set_xticklabels([])
            ax.tick_params(axis="x", labelbottom=False)

        if j == 0:
            ax.set_ylabel(
                r"Perturbation $\delta u_2$",
                fontsize=AXLAB_FS)
            ax.tick_params(axis="y", labelsize=TICK_FS)
        else:
            ax.set_yticklabels([])
            ax.tick_params(axis="y", labelleft=False)

        ax.tick_params(which="both", direction="in", length=3.5, width=0.7)

        for spine in ax.spines.values():
            spine.set_linewidth(0.7)

        axes.append(ax)

    # ── colorbar ───────────────────────────��─────────────────────────────────
    if hm_mappable is not None:
        cb_left = left + ncols * (panel_w_frac + gap_frac) - gap_frac + cb_gap_frac
        cax = fig.add_axes([cb_left, bottom, cb_w_frac, panel_h_frac])
        cb = fig.colorbar(hm_mappable, cax=cax)
        cb.set_ticks([-10, 0, 4])
        cb.ax.tick_params(labelsize=CBTICK_FS)
        cb.outline.set_linewidth(0.7)
        # Title on top of colorbar
        cb.ax.set_title(r"$x_{\min}$", fontsize=CBLABEL_FS, pad=4)

    # ── save main figure ─────────────────────────────────────────────────────
    os.makedirs(os.path.dirname(os.path.abspath(outfile)), exist_ok=True)
    fig.savefig(outfile, dpi=150)
    print(f"Saved main figure -> {outfile}")

    # ── compose with pdflatex (insets) ───────────────────────────────────────
    compose_with_insets(fig, axes, outfile)

    plt.close(fig)


# ═══════════════════════ pdflatex inset composition ═════════════════════════

def compose_with_insets(fig, axes, outfile):
    """
    Overlay fold_scheme.pdf and trans_critical_scheme.pdf as insets on the
    last panel, mimicking the pdflatex composition in the original Julia code.
    Insets are placed at the bottom-LEFT of panel E.
    """
    pdfdir = os.path.join(os.path.dirname(SCRIPT_DIR), "pdffiles", "main")
    fold_pdf = os.path.join(pdfdir, "fold_scheme.pdf")
    tc_pdf = os.path.join(pdfdir, "trans_critical_scheme.pdf")

    if not (os.path.isfile(fold_pdf) and os.path.isfile(tc_pdf)):
        print("  (skipping inset composition -- fold_scheme.pdf or "
              "trans_critical_scheme.pdf not found)")
        return

    if not shutil.which("pdflatex"):
        print("  (skipping inset composition -- pdflatex not found)")
        return

    main_pdf = outfile
    if not main_pdf.endswith(".pdf"):
        print("  (skipping inset composition -- output is not PDF)")
        return

    fig_w, fig_h = fig.get_size_inches()

    ax_e = axes[-1]
    bbox = ax_e.get_position()
    ax_x0 = bbox.x0 * fig_w
    ax_y0 = bbox.y0 * fig_h
    ax_w = bbox.width * fig_w
    ax_h = bbox.height * fig_h

    # Inset geometry — bottom-left of panel E
    INSET_W_FRAC = 0.291
    INSET_PAD_H = 0.03
    INSET_PAD_V = 0.03
    INSET_GAP_V = 0.02
    INSET_H_EST = 0.28

    inset_w = INSET_W_FRAC * ax_w
    x_ins = ax_x0 + INSET_PAD_H * ax_w
    y_tc = ax_y0 + INSET_PAD_V * ax_h
    y_fold = y_tc + INSET_H_EST * ax_h + INSET_GAP_V * ax_h

    tex = (
        r"\documentclass{article}" "\n"
        rf"\usepackage[paperwidth={fig_w:.4f}in,paperheight={fig_h:.4f}in,margin=0pt]{{geometry}}" "\n"
        r"\usepackage{graphicx}" "\n"
        r"\usepackage{tikz}" "\n"
        r"\usetikzlibrary{calc}" "\n"
        r"\pagestyle{empty}" "\n"
        r"\begin{document}%" "\n"
        r"\begin{tikzpicture}[remember picture,overlay]" "\n"
        r"  \node[inner sep=0,anchor=south west] at (current page.south west)" "\n"
        rf"    {{\includegraphics{{{os.path.abspath(main_pdf)}}}}};" "\n"
        r"  \node[inner sep=0,anchor=south west]" "\n"
        rf"    at ($(current page.south west)+({x_ins:.4f}in,{y_tc:.4f}in)$)" "\n"
        rf"    {{\includegraphics[width={inset_w:.4f}in]{{{os.path.abspath(tc_pdf)}}}}};" "\n"
        r"  \node[inner sep=0,anchor=south west]" "\n"
        rf"    at ($(current page.south west)+({x_ins:.4f}in,{y_fold:.4f}in)$)" "\n"
        rf"    {{\includegraphics[width={inset_w:.4f}in]{{{os.path.abspath(fold_pdf)}}}}};" "\n"
        r"\end{tikzpicture}%" "\n"
        r"\end{document}" "\n"
    )

    try:
        with tempfile.TemporaryDirectory() as tmpdir:
            tex_path = os.path.join(tmpdir, "combined.tex")
            with open(tex_path, "w") as f:
                f.write(tex)
            for _ in range(2):
                subprocess.run(
                    ["pdflatex", "-interaction=nonstopmode",
                     f"-output-directory={tmpdir}", tex_path],
                    stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                    check=False)
            composed = os.path.join(tmpdir, "combined.pdf")
            if os.path.isfile(composed):
                shutil.copy2(composed, outfile)
                print(f"  Composed with insets -> {outfile}")
            else:
                print("  (pdflatex composition failed -- keeping main figure)")
    except Exception as e:
        print(f"  (pdflatex composition error: {e} -- keeping main figure)")


# ═══════════════════════════════ CLI ════════════════════════════════════════

def main():
    data_dir = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_DATA_DIR
    outfile = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_OUTFILE

    if not os.path.isdir(data_dir):
        print(f"Error: data directory '{data_dir}' not found.\n"
              f"Run generate_n2_boundary_data.jl first.")
        sys.exit(1)

    meta, xs, ys, panels = load_data(data_dir)
    make_figure(meta, xs, ys, panels, outfile)


if __name__ == "__main__":
    main()
